### ISSUE TITLE
Issue with progress color on wave

### ISSUE THREAD

**Issue by fredlepilot** [beotiger/justwave#1]
I noticed that sometimes the progress image has the wave and background color switched... after many test and research, I had to add in JustWave.class right after the imagecopy, this : 
imagepalettecopy($this->progressImg, $this->waveImg);

(without this, sometimes both palette were not identical, messing with the imagecolorset).
hopefully it will help

**Comment by beotiger** [comment]
Thank you very much for noticing. The issue has been corrected.
