### ISSUE TITLE
Not display in mp3 wav

### ISSUE THREAD

**Issue by indujuly** [beotiger/justwave#3]
Mp3 wave image is not displaying. 
What is the reason? 
If there is any code needed?
please reply me soon .....

**Comment by beotiger** [comment]
what error do you get?

**Comment by indujuly** [comment]
Mp3 wave image is not displaying.
What is the reason?
If there is any code needed?
please reply me soon .....

**Comment by indujuly** [comment]
Hi beotiger
I got one error. If I click working example link I got [ "Failed! Message = Conversion failed" ] that message. please reply me soon .....

**Comment by beotiger** [comment]
Is your ffmpeg installation OK?

**Comment by indujuly** [comment]
Yes I installed ffmpeg. but not working in waves formate. pls advice me.

**Comment by beotiger** [comment]
do you have read/write permissions for wavedir directory?

**Comment by indujuly** [comment]
Thanks. It is working well.
Now recorded mp3 is working. But I have to match our live voice with that mp3. How is it possible? Is there any code at jquery. 
Please tell me soon.

**Comment by beotiger** [comment]
What exactly means `match our live voice with that mp3`?
Should we compare waveforms or what? I think it's sound-processing task which of course we can solve by JavaScript means. You should check Web Audio API: http://webaudio.github.io/web-audio-api/

**Comment by indujuly** [comment]
Thank you so much.
