### ISSUE TITLE
Custom play and stop events?

### ISSUE THREAD

**Issue by stenley** [beotiger/justwave#4]
Is this possible? I will make my own Button.

**Comment by beotiger** [comment]
Hi. What exactly do you want? If you can create custom events you can
create them, JustWave never mind.

On Tue, Jan 19, 2016 at 1:36 AM, stenley notifications@github.com wrote:

> Is this possible? I will make my own Button
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beotiger/justwave/issues/4.

## 

beotiger from Tzaritzyn

**Comment by stenley** [comment]
I meant, for example, $ .justwav.play () or so, but I have now done.

I have another problem when I use the side in quick succession invite then shows me the player no longer Waveform on. That's just sometimes so

Sorry for my english but great script!

**Comment by stenley** [comment]
I have send you a mail

**Comment by beotiger** [comment]
Sorry, I can not understand your question.
Write it out in your native language I will try to translate with Google translator.
