### ISSUE TITLE
const FFMPEG_PATH = 'ffmpeg';

### ISSUE THREAD

**Issue by yungcloud** [beotiger/justwave#6]
hey, sorry noob question... my ffmpeg is in /usr/bin/ffmpeg .. should this be the path? 
I haven't been able to get the script to work yet with my configuration.. 

thanks!

**Comment by beotiger** [comment]
/usr/bin/ is in standard Linux path, so you can call ffmpeg directly

**Comment by beotiger** [comment]
always look for log messages and you will solve your problems
