### ISSUE TITLE
error with prepare() on justwave.cli.php

### ISSUE THREAD

**Issue by 0xRoM** [beotiger/justwave#7]
any idea why I'm getting the following?

╰» php justwave/justwave.cli.php tmp/sample-tmp.mp3 wavedir=tmp/ width=450 height=75 

justwave/justwave.cli.php - PHP command line audio waveform generation.
Generates waveforms from any media files (audio/video) and outputs them to png files.

Creating wave for tmp/sample-tmp.mp3PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /opt/SmartAlarm/justwave/JustWave.class.php:504
Stack trace:
#0 /opt/SmartAlarm/justwave/JustWave.class.php(638): JustWave->cache()
#1 /opt/SmartAlarm/justwave/justwave.cli.php(51): JustWave->create('tmp/sample-tmp....')
#2 {main}
  thrown in /opt/SmartAlarm/justwave/JustWave.class.php on line 504

**Comment by beotiger** [comment]
Hi. You do not have SQLite plugin in your PHP installation. Please add one and everything will work fine.
